version: '3.8'

services:
  mysql-service:
    image: mysql:8.4
    container_name: contenedormysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: juanchest
      MYSQL_PASSWORD: wpass 
    volumes:
      - C:\Users\JuanChest\Documents\Programación\Construcción y evolución del Software\2025B-ISWD633-practica5\bd:/var/lib/mysql
    networks:
      - net-wp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 30s

  wordpress-service:
    image: wordpress:6
    container_name: contenedorwordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: contenedormysql 
      WORDPRESS_DB_USER: juanchest
      WORDPRESS_DB_PASSWORD: wpass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - C:\Users\JuanChest\Documents\Programación\Construcción y evolución del Software\2025B-ISWD633-practica5\www:/var/www/html
    networks:
      - net-wp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 50s
    restart: always
    depends_on:
      mysql-service:
        condition: service_healthy
volumes:
  mysql-data:
  wordpress-vol:

networks:
  net-wp:
    driver: bridge
